### ISSUE TITLE
ES2015 Support

### ISSUE THREAD

**Issue by TheOpenDevProject** [mobermeyer/DocStubsJs#14]
@mobermeyer Thanks for this really cool extension, I have forked the project to breathe some new life into it and will be adding ES2015 support. Will be opening a PR when its done. hopefully it gets merged back into the project.

**Comment by mobermeyer** [comment]
Thanks! I would greatly appreciate your help. I haven't had any time to work on it, but I'll keep an eye out for your PR. Let me know if you have any questions, and please don't judge my code too harshly :)

**Comment by TheOpenDevProject** [comment]
Yeah your code is a little hard to understand. I'm sure ill be able to just debug it to see whats going on and work backwards from there. I would like to know the basic call process for when you detect say a comment in the buffer. The only thing blocking your code from working within ES6 classes is the fact that you have hard coded `function` in a regex which is not the new ES6 syntax.

``` javascript
/**This class does FooBar things*/
class MyClass{
    /**
     * 
     * @param {T} sampleOne
     * @param {T} sampleTwo
     */
    constructor(sampleOne,sampleTwo){

    }

      /**
     * 
     * @param {T} sampleOne
     * @param {T} sampleTwo
     */
    aNewFunction(sampleOne,sampleTwo){
    }
}
```

If I find your code is to hard to work with I might do a re-write for ECMA2015, hopefully I don't have to.

**Comment by mobermeyer** [comment]
I can look more closely at the code later, but you might take a look at the TypeScript portion of the code. It handles functions that are similar to that syntax. (If not the same - I don't use much TypeScript)

**Comment by TheOpenDevProject** [comment]
Well no TS is something different to ECMA2015. ECMA2015 still does not contain type enforcement.

**Comment by mobermeyer** [comment]
Yes, I am aware of that. However, TypeScript does not have to include type declarations - meaning that the code sample you included above is actually valid TypeScript. This extension (should) handle that syntax, but only if it detects that the language of the file is TypeScript. It should be possible to adapt the current TypeScript check for the existence of a function to work for ECMA2015.

**Comment by TheOpenDevProject** [comment]
Now thats interesting, ill give that a shot.

**Comment by TheOpenDevProject** [comment]
Was unable to understand the code that runs this thing as its very messy, If you would be able to make the changes I would love to test them @mobermeyer.

**Comment by fredbutters** [comment]
+1 on the ES2015 support. Great extension otherwise!

**Comment by TheOpenDevProject** [comment]
I have since moved to another extension as a developer. Closing.
