### ISSUE TITLE
I can't get this to work at all with Typescript and VS 13

### ISSUE THREAD

**Issue by NCARalph** [mobermeyer/DocStubsJs#2]
I've installed DocStubsJs in Visual Studio update 4 community edition and it is shown in the extensions list, however, I can't get it to do anything. Here are some code examples:

```
///
constructor(public device?: WEBCL.WebCLDevice) {

constructor(public device?: WEBCL.WebCLDevice) {
    ///

/**
setupProgramFromElement(htmlID: string, kernelNames: string[]) {

setupProgramFromElement(htmlID: string, kernelNames: string[]) {
    /**
```

**Comment by mobermeyer** [comment]
Thanks, currently TypeScript support is limited. This will be fixed in the next release. (Hopefully in the next week or so)

**Comment by mobermeyer** [comment]
Support should be much better in the latest release. Let me know if you find any more issues in TypeScript.
