### ISSUE TITLE
@returns not working properly in 2.1.1?

### ISSUE THREAD

**Issue by runningbug** [mobermeyer/DocStubsJs#8]
Hi, 

Very useful tool, saves a lot of typing! Thanks for making it.

Since upgrading to 2.1.1 DocStubsJS isn't generating the @returns line for me. The @param lines are fine. Downgrading to 2.1.0 fixes this. 

Using vs2015 community.

**Comment by mobermeyer** [comment]
Thanks.

Do you have return tags set to be auto-generated or always generated in your settings?

**Comment by runningbug** [comment]
thanks for the reply

It is set to "Auto".

If i set to "always" it doesn't make any difference.

**Comment by mobermeyer** [comment]
Thanks, I was able to reproduce this in some cases, but on some functions it worked fine. The "auto" feature has never been 100% reliable, but where it fails, I would expect it to generate the return tag when "always" was specified. I can look into this tonight.

**Comment by mobermeyer** [comment]
I've just released a new version that should be better at detecting return statements. Please let me know if this fixes the issue, or if you are still having the same problem (since I wasn't able to reproduce the issue exactly as you described).

**Comment by runningbug** [comment]
Hi Michael,

Yes that's fixed it.

Thanks for the very quick update!
