### ISSUE TITLE
Cursor position on comment generation

### ISSUE THREAD

**Issue by Gambero81** [mobermeyer/DocStubsJs#9]
When comment generation occur (typing /*\* ) cursor location is set at the end of the comment block:

/**
     \* 
     */|<-- Here!

would be correct to set the cursor location at the beginning of comment description allowing you to write immediately comment description:

/**
     \* |<-- Here!
     */

Thanks

**Comment by mobermeyer** [comment]
Yes, I agree. I think this is something I looked into a long time ago, but never successfully implemented. I'll have to take another look at it.

**Comment by mazong1123** [comment]
That should not be complicated in my mind. I noticed this issue when I sent last pull request. I remember I've fixed this in an elegant way but didn't include it in my last pull request. I'll take a look at it either.

**Comment by mobermeyer** [comment]
Yes, absolutely. I remember attempting this before. I thought it should be easy. VS SDK includes some Caret position helpers that I thought would make it trivial, but I must have been missing something because I never could seem to get it to work.

**Comment by mobermeyer** [comment]
This has been implemented and will be available in the next release. Thanks for posting!
